openapi: 3.1.0
info:
  title: La Mascotera · Bridge Dux
  version: "1.0.0"

servers:
  - url: https://bridge-dux.onrender.com

security:
  - ApiKeyAuth: []

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization

  schemas:
    DuxOk:
      type: object
      description: "Respuesta passthrough desde Dux"
      properties: {}
      additionalProperties: true

    DuxError:
      type: object
      description: "Formato de error del bridge"
      properties:
        error:
          type: string
        detail:
          type: string
      additionalProperties: true

    CrearPedidoBody:
      type: object
      required: [clienteId, items]
      properties:
        clienteId:
          type: integer
        observaciones:
          type: string
        externalId:
          type: string
          description: "Idempotencia: clave única del pedido"
        items:
          type: array
          items:
            type: object
            required: [itemId, cantidad]
            properties:
              itemId:
                type: integer
              cantidad:
                type: number
              precio:
                type: number

paths:
  /health:
    get:
      operationId: health
      summary: Healthcheck (sin auth)
      security: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean

  /duxc/items:
    get:
      operationId: buscar_items
      tags: [Items]
      summary: Lista items desde Dux
      description: Devuelve el JSON tal cual responde Dux. Acepta query params de Dux como `offset`, `limit`, `buscar`, etc.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DuxOk"
        "4XX":
          description: Error del cliente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DuxError"
        "5XX":
          description: Error del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DuxError"

  /duxc/facturas:
    get:
      operationId: listar_facturas
      tags: [Ventas]
      summary: Lista facturas
      parameters:
        - in: query
          name: fechaDesde
          schema: { type: string }
        - in: query
          name: fechaHasta
          schema: { type: string }
        - in: query
          name: idEmpresa
          schema: { type: integer }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DuxOk"
        "4XX":
          description: Error del cliente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DuxError"
        "5XX":
          description: Error del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DuxError"

  /duxc/pedido:
    post:
      operationId: crear_pedido
      tags: [Ventas]
      summary: Crea un pedido en Dux
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CrearPedidoBody"
      responses:
        "200":
          description: Creado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DuxOk"
        "4XX":
          description: Error del cliente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DuxError"
        "5XX":
          description: Error del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DuxError"
